apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: leil9os89-python
  janus-idp.io/tekton: leil9os89-python
  backstage.io/kubernetes-id: leil9os89-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: leil9os89-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
