apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: leil9os89-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: leil9os89-python 
  name: leil9os89-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: leil9os89-python 
