apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: leil9os89-python-gitops
  description: This is GitOps manifest for leil9os89-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=leil9os89-python
    backstage.io/kubernetes-id: leil9os89-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: leil9os89-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:leil9os89-python
